import './globals.css'
import Header from '../components/Header'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Mega Flix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-primary'>
        <Header />
        <div className='max-w-[1920px] m-auto min-h-screen'>
        {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
