import './globals.css'
import Header
 from './components/Header'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black'>
        <Header />
        <div className='max-w-[1920px] m-auto min-h-screen'>
        {children}
        </div>
      </body>
    </html>
  )
}
